### ISSUE TITLE
Visualiser ma gouvernance : Gestionnaire Département

### ISSUE THREAD

**Issue by ketroadec** [anct-cnum/suite-gestionnaire-numerique#166]
> ### User story

- En tant que Gestionnaire département

- Je veux pouvoir consulter le informations de ma gouvernance

> ### Design

https://www.figma.com/design/IFH80doDOEvJvbMlUnQIOC/%E2%AD%90%EF%B8%8F-Outil-gestionnaire-FNE?node-id=3530-26419&t=HRL8yNPlceDG83XD-4

> ### Règles métiers

**1. Pour accéder aux informations de ma gouvernance, je clique sur le menu "Gouvernances" dans le menu vertical**

**2. La page contient une entête**        
        - Un titre : "Inclusion numérique - " avec le département correspondant à la gouvernance (même département que celui de rattachement à l'utilisateur connecté avec le rôle gestionnaire département)
        - Une section indiquant le nombre de membres de la gouvernance (uniquement les membres faisant partie de la gouvernance mais pas les suggérés ou souhaitant participer). Cette section contient un lien "Voir les membres" qui renvoie vers la page de gestion des membres d'une gouvernance
        - Une section indiquant le nombre de feuilles de route de la gouvernance. Cette section contient un lien "Voir la feuille de route" si il n'y en a qu'une ou "Voir les feuilles de route" si il y en a plusieurs. Le lien renvoie vers la page de gestion des feuilles de routes
        - Une section "Note privée" qui affiche la dernière note saisie. Au clic sur la section, on ouvrira le drawer de mise à jour de la note
 
**3. Une section "Comitologie" qui contient :**         
        - Un bouton "Ajouter" qui permet d'ouvrir le drawer d'ajout d'un comité        - Une liste des comités dont la date du prochain comité, le nom du comité ainsi que la périodicité
        - Au clic sur une ligne, on ouvre le drawer détail/modification

**4. Section "Membres"**
        - Un bouton "Gérer" qui renvoie vers la page de gestion des membres de la gouvernances
        - La liste des membres de la gouvernance avec le nom du membre, la typologie de structure du membre, les rôles dans la gouvernance du membre (on affiche uniquement les membres faisant partie de la gouvernance, on exclu les suggérés ou souhaitant participer)
        - Au clic sur une ligne, on ouvrira le drawer de détail d'un membre

**5. Une section "Feuilles de route"**
        - Un bouton "Gérer" qui renvoie vers la page de gestion "Feuilles de route"
        - La liste des feuilles de route rattachées à la gouvernance avec le nom de la feuille de route, le nombre d'actions et le budget global de la feuille de route
        - Au clic sur une ligne, on affichera le drawer de détail d'une feuille de route

**6. Une section "Note de contexte"**       
        - Un bouton "Modifier" qui ouvrira le drawer de modification de la note de contexte
        - On affiche également la date de dernière modification ainsi que l'utilisateur qui a effectué la modification
        - Le texte de la note de contexte dans un encadré bleu
        - Un bouton "Lire plus" pour visualiser l'entièreté de la note saisie

**Comment by NerOcrO** [comment]
- le DSFR n'offre pas de possibilité de faire le "lire plus" de la note de contexte, je ne pense pas qu'il soit obligatoire pour le moment, peut on le faire plus tard ?
- étant donné que j'ai bouchonné une gouvernance et que j'ai fait toutes les conditions sur les différentes sections alors la partie "vide" ne s'affiche plus, est-ce que je fais deux liens dans le menu latéral ou c'est ok pour le moment ?
- quels sont les différents types de membre et les différents icones associés ?
- est-ce que c'est ok pour toi de mettre les carrés du haut même quand c'est 0 ? cela simplifie le dev et les tests

**Comment by ketroadec** [comment]
- Non pour le coup les notes contextes qui sont déjà en bdd sont très longues, il faut vraiment le "Lire plus" sur cette partie dès la première version
-
- Si tous les blocs de la gouvernance sont vides alors on cache la zone avec les carrés en haut, si un des blocs à une donnée alors on affiche les blocs en haut même si le chiffre est 0

**Comment by NerOcrO** [comment]
Le résumé de la note de contexte est du HTML et c'est assez compliqué de couper du HTML.
Peut on l'afficher en texte brute et couper à un certain nombre de caractère ?
Si oui combien ?

**Comment by ketroadec** [comment]
350 caractères, on affinera en voyant le rendu

**Comment by meha-octo** [comment]
Vu avec @Bourchanin : pour le point **4. Section "Membres"** :

- on n'affiche pas tous les membres, uniquement les **co-porteurs**, préfecture départementale en premier, autres co-porteurs à la suite triés par ordre alphabétique du nom,

- on n'affiche pas un décompte des rôles (x co-porteurs, y bénéficiaires etc), mais : le nombre de co-porteurs, le nombre total de membres, le nombre de candidats, et le nombre de membres suggérés.
