### ISSUE TITLE
Menu latéral Gestionnaire département

### ISSUE THREAD

**Issue by ketroadec** [anct-cnum/suite-gestionnaire-numerique#249]
> ### User story

- En tant que Gestionnaire département
- Je veux visualiser le menu pour naviguer au sein de Mon Inclusion Numérique

> ### Design

https://www.figma.com/design/IFH80doDOEvJvbMlUnQIOC/%E2%AD%90%EF%B8%8F-Outil-gestionnaire-FNE?node-id=6470-39783&t=dTZZOb8YmJQok95S-4

> ### Règles métiers

1. Les intitulés des menus sont identiques pour tous les rôles de l'application
2. Le menu est constitué de : 
     - Un menu "Gouvernance" : 
            +  Lorsque je clique sur le menu, j'accède à la gouvernance dans laquelle je suis membre (mon département) (déjà fait ✅ )
      - Des sous-menus s'affichent après avoir cliqué sur "Gouvernance", ils sont nommés "Membres" 🟢 
            + Lorsque je clique sur "Membres", la liste des membres de la gouvernance dont je suis membre s'affiche  🟢 
      - Des sous-menus s'affichent après avoir cliqué sur "Gouvernance", ils sont nommés "Feuilles de route" 🟢 
            + Lorsque je clique sur "Feuilles de route", la page avec la liste des feuilles de routes de ma gouvernance s'affiche 🟢  
      - Un menu "Financements" 🟢 
            + Lorsque je clique sur "Financements", la page "Demandes de financements" s'affiche avec toutes les demandes de financement qui concernent ma gouvernance  🟢
      - Un menu "Bénéficiaires" 🟢 
            + Lorsque je clique sur "Bénéficiaires", la page "Membres bénéficiaires" s'affiche avec la liste des tous les bénéficiaires de ma gouvernance  🟢
      - Un menu "Aidants et médiateurs" 🟢  
            + Lorsque je clique sur "Aidants et médiateurs", la liste des aidants et médiateurs s'affiche. Je ne pourrais voir que les aidants et médiateurs de mon département  🟢
      - Un menu "Lieux d'inclusion" 🟢 
            + Lorsque je clique sur "Lieux d'inclusion", la liste des lieux d'inclusion numérique s'affiche. Je ne pourrais voir que les lieux de mon département  🟢
      - Un menu "Export de données"  🟢
            + Lorsque je clique sur "Export de données", j'accède à une interface type tableur sur laquelle je peux filtrer des données et les exporter en csv  🟢
      - Un menu "Rapports" 🟢
            + Lorsque je clique sur "Rapports", j'accède à un ensemble de rapport près conçus permettant d'exporter de la data vision  🟢

----------------------------------

@ketroadec Ticket terminée : attention , la partie responsive n'est pas faite :x:
Si on souhaite que le menu soit responsive , est il possible de mettre un ticket dédier (avec maquette) ❓

**Comment by Ornella452** [comment]
@ketroadec je te confirme que c'est bien la Marianne 👍 
![Image](https://github.com/user-attachments/assets/689708ad-eb8a-45db-8d2e-140c00bb2681)
