### ISSUE TITLE
Visualiser et modifier mes paramètres

### ISSUE THREAD

**Issue by ketroadec** [anct-cnum/suite-gestionnaire-numerique#76]
> ### User story

- En tant que Pilote politique publique, Admin dispositif, Instructeur, Gestionnaire région, Gestionnaire département, Support animation, gestionnaire groupement, gestionnaire structure

- Je veux pouvoir visualiser et modifier mes paramètres de compte

> ### Design

https://www.figma.com/design/IFH80doDOEvJvbMlUnQIOC/%E2%AD%90%EF%B8%8F-Outil-gestionnaire-FNE?node-id=3166-23347&t=abt6JUFBAOXuYrTP-4

> ### Règles métiers

- Depuis le menu utilisateur, lorsque je clique sur "Mes paramètres" je suis redirigé vers la page de gestion des paramètres
- Dans la section Communication et notifications, on retrouve 2 paramètres : 
       -  Recevoir toutes les notifications sur votre adresse mail : Si ce paramètre est activé, on enverra toutes les notifications par mail unitairement. Si il est désactivé, on enverra pas de mail à chaque action
       - Recevoir un récapitulatif hebdomadaire sur votre adresse mail : Si ce paramètre est activé, on enverra un mail par semaine avec un récapitulatif des notifications en attente sur l'application. S'il n'est pas activé, on enverra pas ce mail récapitulatif
       - Si les 2 sont activés, on enverra les 2 types de notifications
       - Si aucun n'est activé, on enverra aucunes notifications par mail
       - Par défaut, les 2 paramètres sont activés à la création du compte

- Dans la section "Affichage", un switch est disponible pour changer entre le mode clair et le mode sombre

> ### Scénarios fonctionnels

> ## Technique

**Comment by meha-octo** [comment]
@ketroadec le thème par défaut doit-il être celui du système ?
